server.port: 8080
spring.profiles.active: local
server.servlet.context-path: /muse
# undertow
server.undertow.threads.worker: 96
server.undertow.max-http-post-size: 104857600
# spring
spring.servlet.multipart.max-file-size: 100MB
spring.servlet.multipart.max-request-size: 100MB
management.endpoints.web.exposure.include: prometheus
# datasource
spring.datasource.type: com.zaxxer.hikari.HikariDataSource
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.sql.init.mode: never
# mybatis plus
mybatis-plus.typeAliasesPackage: com.fngry.muse.dao.entity
mybatis-plus.global-config.db-config.id-type: auto
mybatis-plus.configuration.map-underscore-to-camel-case: true
mybatis-plus.configuration.cache-enabled: false
# log
logging.config: classpath:log4j2_${env.name}.xml

