
spring.datasource.url: jdbc:mysql://${db.host}/bjminsu?useSSL=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true
spring.datasource.username: ${db.username}
spring.datasource.password: ${db.password}