apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-service-muse
spec:
  minReadySeconds: 20
  replicas: 2
  selector:
    matchLabels:
      app: springboot-service-muse
  template:
    metadata:
      labels:
        app: springboot-service-muse
    spec:
      containers:
        - name: springboot-service-muse
          image: localhost:5000/muse:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /data/logs
              name: log-storage
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx256m -Dserver.port=8080 -Dspring.profiles.active=prod"
          resources:
            requests:
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /muse/demo/hello?userName=abc
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /muse/demo/hello?userName=abc
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          lifecycle:
            preStop:
              exec:
                command:
                  - bash
                  - -c
                  - "curl http://localhost:8080/muse/demo/hello?userName=bye"
      volumes:
        - name: log-storage
          hostPath:
            path: /data/logs

---
kind: Service
apiVersion: v1
metadata:
  name: springboot-service-muse
spec:
  selector:
    app: springboot-service-muse
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
